// Feature: mvp-saas-platform, Property 5: Storage path format

/**
 * Validates: Requirements 4.7
 *
 * Property 5: For any combination of `team_id`, `userId`, and `filename`, the
 * storage path generated by `uploadMediaItem` SHALL match the pattern
 * `{team_id}/{userId}/{epoch_ms}_{filename}` where `epoch_ms` is a positive
 * integer representing milliseconds since Unix epoch.
 *
 * Implementation note:
 *   `uploadMediaItem` constructs the path inline as:
 *     `${teamId}/${userId}/${Date.now()}_${file.name}`
 *
 *   Since `buildStoragePath` is not exported from mediaService, we mirror the
 *   exact same construction logic as a pure function here so the property can
 *   be tested without side effects or Supabase calls.
 *
 *   Example path: 550e8400-e29b-41d4-a716-446655440000/auth-uid-123/1700000000000_hero.png
 */

import { describe, it, expect } from 'vitest'
import * as fc from 'fast-check'

// ─── Pure helper: mirrors the path construction in uploadMediaItem ────────────

/**
 * Mirrors the exact expression used in mediaService.ts `uploadMediaItem`:
 *   `const path = \`${teamId}/${userId}/${Date.now()}_${file.name}\``
 *
 * Accepts an explicit `epochMs` parameter so the property can assert on the
 * epoch value without relying on wall-clock time.
 */
function buildStoragePath(teamId: string, userId: string, filename: string, epochMs?: number): string {
  const ts = epochMs ?? Date.now()
  return `${teamId}/${userId}/${ts}_${filename}`
}

// ─── Arbitraries ─────────────────────────────────────────────────────────────

/** Valid Unix epoch in milliseconds: 1 ms to ~year 2100 */
const epochMsArb: fc.Arbitrary<number> = fc.integer({ min: 1, max: 4_102_444_800_000 })

/** Filenames that do not contain '/' (path separator) */
const filenameArb: fc.Arbitrary<string> = fc
  .string({ minLength: 1, maxLength: 200 })
  .filter((s) => !s.includes('/'))

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('Property 5 — Storage path format', () => {

  // ── Property 5 (canonical): full regex match from design doc ─────────────────

  it(
    'storage path always matches {team_id}/{userId}/{epoch}_{filename} (100 runs)',
    () => {
      /**
       * **Validates: Requirements 4.7**
       *
       * For any teamId (UUID), userId, and filename, the constructed storage
       * path SHALL match the regex:
       *   ^{teamId}/{userId}/\d+_{filename}$
       *
       * This is the exact property shown in the design document.
       */
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.string({ minLength: 1 }),
          fc.string({ minLength: 1 }),
          (teamId, userId, filename) => {
            const path = buildStoragePath(teamId, userId, filename)
            // Escape any regex special characters in userId and filename
            // (teamId is a UUID so it never contains special regex chars)
            const escapedUserId = userId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
            const escapedFilename = filename.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
            expect(path).toMatch(
              new RegExp(`^${teamId}/${escapedUserId}/\\d+_${escapedFilename}$`),
            )
          },
        ),
        { numRuns: 100 },
      )
    },
  )

  // ── Property 5a: path starts with {teamId}/ ───────────────────────────────────

  it(
    'path always starts with {teamId}/ (100 runs)',
    () => {
      /**
       * **Validates: Requirements 4.7**
       *
       * The first path segment SHALL always be the teamId, ensuring storage
       * objects are namespaced per tenant.
       */
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.string({ minLength: 1 }),
          filenameArb,
          epochMsArb,
          (teamId, userId, filename, epochMs) => {
            const path = buildStoragePath(teamId, userId, filename, epochMs)
            expect(path.startsWith(`${teamId}/`)).toBe(true)
            expect(path.split('/')[0]).toBe(teamId)
          },
        ),
        { numRuns: 100 },
      )
    },
  )

  // ── Property 5b: second segment is {userId} ───────────────────────────────────

  it(
    'second path segment is always {userId} (100 runs)',
    () => {
      /**
       * **Validates: Requirements 4.7**
       *
       * The second path segment SHALL always be the userId, scoping the file
       * within the tenant's namespace to the uploading user.
       */
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.string({ minLength: 1 }).filter((s) => !s.includes('/')),
          filenameArb,
          epochMsArb,
          (teamId, userId, filename, epochMs) => {
            const path = buildStoragePath(teamId, userId, filename, epochMs)
            const segments = path.split('/')
            expect(segments[1]).toBe(userId)
          },
        ),
        { numRuns: 100 },
      )
    },
  )

  // ── Property 5c: third segment matches {epoch_ms}_{filename} ─────────────────

  it(
    'third segment always matches {epoch_ms}_{filename} (100 runs)',
    () => {
      /**
       * **Validates: Requirements 4.7**
       *
       * The third path segment SHALL match `{epoch_ms}_{filename}` where
       * `epoch_ms` is a positive integer and `filename` is the original
       * file name.
       */
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.string({ minLength: 1 }).filter((s) => !s.includes('/')),
          filenameArb,
          epochMsArb,
          (teamId, userId, filename, epochMs) => {
            const path = buildStoragePath(teamId, userId, filename, epochMs)
            const segments = path.split('/')
            // The third segment is everything after the second '/'
            // (filename itself may not contain '/' due to the filter above)
            const thirdSegment = segments[2]
            expect(thirdSegment).toBe(`${epochMs}_${filename}`)
          },
        ),
        { numRuns: 100 },
      )
    },
  )

  // ── Property 5d: epoch_ms is a positive integer ───────────────────────────────

  it(
    'epoch_ms prefix in path is always a positive integer (100 runs)',
    () => {
      /**
       * **Validates: Requirements 4.7**
       *
       * The epoch_ms component of the third path segment SHALL be a positive
       * integer (> 0), representing milliseconds since the Unix epoch.
       */
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.string({ minLength: 1 }).filter((s) => !s.includes('/')),
          filenameArb,
          epochMsArb,
          (teamId, userId, filename, epochMs) => {
            const path = buildStoragePath(teamId, userId, filename, epochMs)
            const thirdSegment = path.split('/')[2]
            // The epoch prefix is the part before the first '_'
            const underscoreIdx = thirdSegment.indexOf('_')
            expect(underscoreIdx).toBeGreaterThan(-1)
            const epochStr = thirdSegment.slice(0, underscoreIdx)
            const parsedEpoch = parseInt(epochStr, 10)
            // Must be a valid integer
            expect(Number.isInteger(parsedEpoch)).toBe(true)
            // Must be positive
            expect(parsedEpoch).toBeGreaterThan(0)
            // Must round-trip back to the original epochMs
            expect(parsedEpoch).toBe(epochMs)
          },
        ),
        { numRuns: 100 },
      )
    },
  )

  // ── Property 5e: epoch_ms is a valid Unix timestamp in milliseconds ───────────

  it(
    'epoch_ms is a valid Unix timestamp in milliseconds (100 runs)',
    () => {
      /**
       * **Validates: Requirements 4.7**
       *
       * The epoch_ms value SHALL represent a valid Unix timestamp in
       * milliseconds — i.e., it SHALL be a finite positive number that, when
       * divided by 1000, produces a valid Date (not NaN or Invalid Date).
       */
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.string({ minLength: 1 }).filter((s) => !s.includes('/')),
          filenameArb,
          epochMsArb,
          (teamId, userId, filename, epochMs) => {
            const path = buildStoragePath(teamId, userId, filename, epochMs)
            const thirdSegment = path.split('/')[2]
            const underscoreIdx = thirdSegment.indexOf('_')
            const epochStr = thirdSegment.slice(0, underscoreIdx)
            const parsedEpoch = parseInt(epochStr, 10)

            // Must be finite
            expect(Number.isFinite(parsedEpoch)).toBe(true)
            // Must be positive
            expect(parsedEpoch).toBeGreaterThan(0)
            // Must produce a valid Date when treated as milliseconds
            const date = new Date(parsedEpoch)
            expect(date.getTime()).not.toBeNaN()
            expect(date.getTime()).toBe(parsedEpoch)
          },
        ),
        { numRuns: 100 },
      )
    },
  )

  // ── Property 5f: path has exactly three segments ─────────────────────────────

  it(
    'path always has exactly three slash-separated segments (100 runs)',
    () => {
      /**
       * **Validates: Requirements 4.7**
       *
       * The storage path SHALL have exactly three segments separated by '/':
       *   [teamId, userId, {epoch_ms}_{filename}]
       *
       * This holds as long as teamId, userId, and filename do not contain '/'.
       * teamId is a UUID (no slashes), userId and filename are filtered here.
       */
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.string({ minLength: 1 }).filter((s) => !s.includes('/')),
          filenameArb,
          epochMsArb,
          (teamId, userId, filename, epochMs) => {
            const path = buildStoragePath(teamId, userId, filename, epochMs)
            const segments = path.split('/')
            expect(segments).toHaveLength(3)
          },
        ),
        { numRuns: 100 },
      )
    },
  )
})
